using DataFrames, Random
using FileIO, JLD2, CSV

# function which generates a directory and file paths for saving data (the path uses nspins, alpha and the current date and time)
function basedirectory(experiment::String, lattice::LatticeSettings, date::Dates.DateTime)
    # generate a directory name
    dir = "data/$experiment/L$(lattice.Lx)L$(lattice.Ly)/$(Dates.format(date, "yyyymmdd-HH:MM:SS"))"
    return dir
end

basedirectory(experiment::String, lattice::LatticeConfig, date::Dates.DateTime) = basedirectory(experiment, lattice.settings, date)

# write files to disk
function writeFiles(settings::UltraFastSettings, energies, stddevs, observables::NamedTuple; elapsed = nothing, seed = nothing, model=nothing)
    # make date
    date = Dates.now()
    # generate the paths
    dir = basedirectory(settings.experiment, settings.lattice, date)
    # create the directory
    mkpath(dir)
    # write the data
    energydataframe = DataFrame(realenergy=real.(energies),
        imaginaryenergy=imag.(energies),
        realstddev=real.(stddevs),
        imaginarystddev=imag.(stddevs),
    )

    # write the data to CSV
    CSV.write(joinpath(dir, "energy.csv"), energydataframe)

    # write the settings to JSON using jsonsettings
    jsonsettings(joinpath(dir, "settings.json"), settings, date; elapsed=elapsed, seed=seed)

    # transform NamedTuple where value(o) is run on every item

    # loop over the observables and write every to a CSV file called observable_name.csv
    for (name, obs) in zip(keys(observables), observables)
        CSV.write(joinpath(dir, "observable_$name.csv"), dataframe(obs))
    end

    #CSV.write(joinpath(dir, "observables.csv"), )

    if isnothing(model) == false
        # write the model to JLD2
        jldsave(joinpath(dir, "model.h5"); model=model)
    end
end

# # function to get the paths generated by generatePaths and return a list per date
# function getPaths(nspins, alpha)
#     # get the directory and file paths
#     dir = "data/n$(nspins)alpha$alpha"
#     # get the list of directories but only if they are directories
#     files = readdir(dir)

#     # the directory names that we consider will only have the following format: yyyymmdd-HH:MM:SS
#     dirs = filter(x -> occursin(r"^\d{8}-\d{2}:\d{2}:\d{2}$", x), files)

#     # parse the dates and write into a dictionary
#     data = Dict()

#     for datestring in dirs
#         date = Dates.DateTime(datestring, "yyyymmdd-HH:MM:SS")
#         data[date] = joinpath(dir, datestring, "data.h5") 
#     end

#     return data
# end

# # function to get the latest data based on nspins and alpha
# function getLatestData(nspins, alpha)
#     # get the paths
#     paths = getPaths(nspins, alpha)
#     # get the latest date
#     latest = maximum(keys(paths))
#     # return the latest data
#     return paths[latest], latest
# end

# # function to read latest file from disk
# function readLatestFile(nspins, alpha)
#     # get the latest data
#     data = getLatestData(nspins, alpha)
#     # read the data
#     jldopen(data) do file
#         return file["energies"], file["stddevs"], file["settings"]
#     end
# end